### ISSUE TITLE
ZabbixMetric send failed

### ISSUE THREAD

**Issue by Sisphyus** [adubkov/graphite-to-zabbix#11]
Successfully get graphite data and build ZabbixMetric data as follows. but always get response from zabbix server told that all metrics send failed.

11/14/2017 11:27:09 AM ZabbixMetric: {"host": "CAS0530000221", "value": "186427.0", "key": "graphite[virt.instance_1.disk_ops.sda.read]", "clock": 1510629870}
11/14/2017 11:27:09 AM ZabbixMetric: {"host": "CAS0530000221", "value": "50724838.5", "key": "graphite[virt.instance_1.disk_ops.sda.write]", "clock": 1510629870}
11/14/2017 11:27:09 AM Messages: ['{"host": "CAS0530000221", "value": "186427.0", "key": "graphite[virt.instance_1.disk_ops.sda.read]", "clock": 1510629870}', '{"host": "CAS0530000221", "value": "50724838.5", "key": "graphite[virt.instance_1.disk_ops.sda.write]", "clock": 1510629870}']
11/14/2017 11:27:09 AM Request: {"request":"sender data","data":[{"host": "CAS0530000221", "value": "186427.0", "key": "graphite[virt.instance_1.disk_ops.sda.read]", "clock": 1510629870},{"host": "CAS0530000221", "value": "50724838.5", "key": "graphite[virt.instance_1.disk_ops.sda.write]", "clock": 1510629870}]}
11/14/2017 11:27:09 AM Packet [str]: ZBXD{"request":"sender data","data":[{"host": "CAS0530000221", "value": "186427.0", "key": "graphite[virt.instance_1.disk_ops.sda.read]", "clock": 1510629870},{"host": "CAS0530000221", "value": "50724838.5", "key": "graphite[virt.instance_1.disk_ops.sda.write]", "clock": 1510629870}]}
11/14/2017 11:27:09 AM Packet [hex]: 5a:42:58:44:1:19:1:0:0:0:0:0:0:7b:22:72:65:71:75:65:73:74:22:3a:22:73:65:6e:64:65:72:20:64:61:74:61:22:2c:22:64:61:74:61:22:3a:5b:7b:22:68:6f:73:74:22:3a:20:22:43:41:53:30:35:33:30:30:30:30:32:32:31:22:2c:20:22:76:61:6c:75:65:22:3a:20:22:31:38:36:34:32:37:2e:30:22:2c:20:22:6b:65:79:22:3a:20:22:67:72:61:70:68:69:74:65:5b:76:69:72:74:2e:69:6e:73:74:61:6e:63:65:5f:31:2e:64:69:73:6b:5f:6f:70:73:2e:73:64:61:2e:72:65:61:64:5d:22:2c:20:22:63:6c:6f:63:6b:22:3a:20:31:35:31:30:36:32:39:38:37:30:7d:2c:7b:22:68:6f:73:74:22:3a:20:22:43:41:53:30:35:33:30:30:30:30:32:32:31:22:2c:20:22:76:61:6c:75:65:22:3a:20:22:35:30:37:32:34:38:33:38:2e:35:22:2c:20:22:6b:65:79:22:3a:20:22:67:72:61:70:68:69:74:65:5b:76:69:72:74:2e:69:6e:73:74:61:6e:63:65:5f:31:2e:64:69:73:6b:5f:6f:70:73:2e:73:64:61:2e:77:72:69:74:65:5d:22:2c:20:22:63:6c:6f:63:6b:22:3a:20:31:35:31:30:36:32:39:38:37:30:7d:5d:7d
11/14/2017 11:27:09 AM Sending data to ('127.0.0.1', 10051)
11/14/2017 11:27:09 AM Response header: ZBXDZ
11/14/2017 11:27:09 AM Data received: {u'info': u'processed: 0; failed: 2; total: 2; seconds spent: 0.000077', u'response': u'success'}
11/14/2017 11:27:09 AM ('127.0.0.1', 10051) response: {u'info': u'processed: 0; failed: 2; total: 2; seconds spent: 0.000077', u'response': u'success'}

**Comment by adubkov** [comment]
Check that you have zabbix trappers configured for all keys. If zabbix doesn't have configured trapper for a key it will reject that metric.

**Comment by Sisphyus** [comment]
thinks. I missed some of configurations with some keys. It's OK now.
