### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by winderickxeli** [adubkov/graphite-to-zabbix#12]
Hi

Thank for making this software. It fills my exact needs. When setting this up I got an error on the SSL certificate. This is wierd considering I'm using http links in the command. Is an SSL connection forced and can I overrule this error?

command:
```
g2zproxy -z http://zabbix.server -zu User -zp secret -g http://graphite.server/graphite
```

error:
```
http://<servernaam>/graphite/render?from=-5minutes&rawData=true&target=<graphitestring>&format=json 65ms
04/23/2019 01:41:50 PM <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:618)>
```

PS. You should add (pip install) pyyaml as a dependency. This was needed for me to get this running.

**Comment by adubkov** [comment]
Hi,

I don't think that SSL is enforced in app. Are you sure any of those servers doesn't have redirect http to https?

**Comment by winderickxeli** [comment]
Hi

Thanks for the quick response. The Graphite was indeed redirecting to https...
